# DQN疏散系统配置文件

# 环境参数
env:
  width: 36
  height: 30
  fire_zones: [[18, 14], [19, 14], [18, 15], [19, 15], [18, 16], [19, 16]]
  exit_location: [36, 15]
  num_people: 150

# 智能体参数
agent:
  gamma: 0.99
  epsilon: 1.0
  epsilon_min: 0.02
  epsilon_decay: 0.9995
  learning_rate: 0.0001
  batch_size: 32
  target_update_freq: 200
  warmup_steps: 0
  memory_size: 50000

# 训练参数
episodes: 100
update_target_freq: 50
visualization_freq: 25
save_path: "dqn_results" 